name: 证书哈希值自动更新

on:
  schedule:
    # 每天北京时间晚上00:01运行 (UTC+8)，对应UTC时间 16:01
    - cron: '1 16 * * *'
  # 也允许手动触发工作流
  workflow_dispatch:

jobs:
  update-cert-hashes:
    runs-on: ubuntu-latest
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install cryptography
          
      - name: 运行证书检查脚本
        run: python leaf_cert_public_fetcher.py
        
      - name: 提交更新后的哈希值
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ValidAICertificatesHash.json
          # 只在文件有变更时才提交
          git diff --staged --quiet || git commit -m "自动更新API证书哈希值"
          
      - name: 推送更改
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 